version: "3.7"


services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
        - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker_db
    ports:
        - "5432:5432"
    networks:
        - s-network
    volumes:
        - postgres-s-data:/var/lib/postgresql/data

networks:
    s-network:
      driver: bridge

volumes:
    postgres-s-data:


